Allow for customised version of settings for test
Also remove example setting for using sqlite in local test - this isn't
possible as extensions are required to run the system:

    sqlite3.OperationalError: near "EXTENSION": syntax error